### ISSUE TITLE
No confirmation method?

### ISSUE THREAD

**Issue by azulkipli** [uxweb/sweet-alert#10]
Please add this feature

thanks

**Comment by uxweb** [comment]
@azulkipli Hi, as the confirm feature from sweet alert js library requires a javascript callback which will be strange to pass from the php backend, i think this feature could be implemented by publishing the included view and add your custom callback (maybe one that does an ajax request).

Current functionality will only achieve displaying alert messages after an action has happened in the backed.

```
swal({
    title: "Are you sure?",   
    text: "You will not be able to recover this imaginary file!",   
    type: "warning",   
    showCancelButton: true,   
    confirmButtonColor: "#DD6B55",   
    confirmButtonText: "Yes, delete it!",   
    closeOnConfirm: false 
}, function() {
    // Here you can do anything you need when the alert is confirmed
});
```

**Comment by azulkipli** [comment]
ok thanks
