### ISSUE TITLE
Laravel Version

### ISSUE THREAD

**Issue by Rishibansal1998** [uxweb/sweet-alert#101]
Not installing with Laravel 6.0

 - Conclusion: remove laravel/framework v6.0.4
 - Conclusion: don't install laravel/framework v6.0.4

**Comment by JoaoGCNeves** [comment]
I ran the command 
`composer require uxweb/sweet-alert dev-master`
and the installation was successful

**Comment by uxweb** [comment]
@Rishibansal1998 @JoaoGCNeves 

A new tag (2.0.2) was released, there is no need to require dev-master anymore.

Thank you!
