### ISSUE TITLE
Package Install Error in Laravel 6.3.0

### ISSUE THREAD

**Issue by dev-techguy** [uxweb/sweet-alert#102]
uxweb/sweet-alert 2.0.0 requires illuminate/session ~5.0 -> satisfiable by illuminate/session[5.0.x-dev....

**Comment by aamirchaudhary** [comment]
Add this in composer.json and update;
"uxweb/sweet-alert": "dev-master"
its working for me.

**Comment by colbyalbo** [comment]
Same error here.  using the "uxweb/sweet-alert": "dev-master" worked

**Comment by dev-techguy** [comment]
Using **"uxweb/sweet-alert": "dev-master"** in composer.json worked.
![aff22723ab391b694c9bcae65ee2da76](https://user-images.githubusercontent.com/36882600/67623624-356d8780-f830-11e9-963c-6dd19f8190e9.png)

**Comment by joantp** [comment]
> Add this in composer.json and update;
> "uxweb/sweet-alert": "dev-master"
> its working for me.

Gràcies, gràcies, gràcies!

**Comment by aliesmailiCode** [comment]
dont show icons

**Comment by stephan-v** [comment]
Icons are not showing.

**Comment by uxweb** [comment]
@AliEsmaili72  @stephan-v 

A new release is out! There's no need to require dev-master anymore!

Thank you!
