### ISSUE TITLE
SweetAlert warning: "type" option has been deprecated. Please use "icon" instead. 

### ISSUE THREAD

**Issue by anburocky3** [uxweb/sweet-alert#114]
I tried to uninstall and again get the fresh copy by `composer require uxweb/sweet-alert` but still the same problem..

Do i have to manually replace the type to icon?

**Comment by uxweb** [comment]
@anburocky3 

Please update to the new version.

**Comment by anburocky3** [comment]
Sorry was experiencing this issue, restarting with `php artisan serve` fixed the problem... Thank you for commenting.

**Comment by uxweb** [comment]
@anburocky3 

Glad to be of help!
