### ISSUE TITLE
Toast SweetAlert2

### ISSUE THREAD

**Issue by FuriosoJack** [uxweb/sweet-alert#119]
Please Add SweetAlert2

https://sweetalert2.github.io/

![image](https://user-images.githubusercontent.com/26976637/73325528-da777200-421c-11ea-9ec1-807602d00cea.png)

**Comment by uxweb** [comment]
@FuriosoJack 

SweetAlert2 is a different javascript library which has a different api. This package follows some features and conventions from https://sweetalert.js.org.
