### ISSUE TITLE
send customize parameters from Laravel controller

### ISSUE THREAD

**Issue by marioene** [uxweb/sweet-alert#12]
Hi, 
First, great component! :)

I'm using your custom view ("uxweb/sweet-alert": "~1.1"):

```
 @if (Session::has('sweet_alert.alert'))
   <script>
     swal({
        text: "{!! Session::get('sweet_alert.text') !!}",
        title: "{!! Session::get('sweet_alert.title') !!}",
        timer: {!! Session::get('sweet_alert.timer') !!},
        type: "{!! Session::get('sweet_alert.type') !!}",
        showConfirmButton: "{!! Session::get('sweet_alert.showConfirmButton') !!}",
        confirmButtonText: "{!! Session::get('sweet_alert.confirmButtonText') !!}",
        confirmButtonColor: "#AEDEF4"
       // more options
      });
    </script>
   @endif
```

How can I send parameters from my controller to change, for example, Session::get('sweet_alert.showConfirmButton') parameter?

I was trying with the code bellow, but is not working:

```
    public function getDelete($id)
    {
      Session::set('sweet_alert.showConfirmButton', "true");
       Alert::warning('Delete?', '');
       return Redirect('....');
     }
```

**Comment by uxweb** [comment]
Hi @marioene , Thanks!!

I don't understand very well what you are trying to do, can you elaborate more on this? :)

**Comment by marioene** [comment]
@uxweb 
When I click confirmButton.. to call, for example, Delete method from my Controller
When I click Cancel ... to cancel 

Can I call method through ajax in this section?

``` javascript
,function() {
    // Here you can do anything you need when the alert is confirmed
});
```

?

**Comment by uxweb** [comment]
Sure, you can put there any code you need :)
