### ISSUE TITLE
Consider using SweetAlert2 instead of SweetAlert

### ISSUE THREAD

**Issue by limonte** [uxweb/sweet-alert#120]
I would like to propose migrating from SweetAlert to [SweetAlert2](https://github.com/sweetalert2/sweetalert2) - the supported fork of SweetAlert. The original reason for creating SweetAlert2 is the inactivity of SweetAlert: https://stackoverflow.com/a/27842854/1331425 

### Reasons to switch:

1. More great features like toasts which were requested in #119

2. Accessibility (WAI-ARIA) - SweetAlert2 is fully WAI-ARIA compatible and supports all popular screen-readers. Accessibility is a must in 2019, there are a lot of explanatory and tech articles, but this one is truly inspirable: [Software development 450 words per minute](https://www.vincit.fi/en/blog/software-development-450-words-per-minute/)

3. Better buttons contrast is a huge advantage for all users especially for users with vision disabilities. 

4. Better support, average time to resolve an issue:

   - SweetAlert: ![](http://isitmaintained.com/badge/resolution/t4t5/sweetalert.svg)
   - SweetAlert2: ![](http://isitmaintained.com/badge/resolution/sweetalert2/sweetalert2.svg)

5. SweetAlert2 is twice more popular that SweetAlert: https://www.npmtrends.com/sweetalert-vs-sweetalert2

![image](https://user-images.githubusercontent.com/6059356/76957600-be3fa980-691e-11ea-8e07-d5c97074a5c3.png)

---

I can contribute with a PR if needed. After migrating, I can add the link to this project to https://github.com/sweetalert2/sweetalert2#related-community-projects so users can discover it

**Comment by uxweb** [comment]
Awesome, go ahead!
