### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by yousefyahya** [uxweb/sweet-alert#129]

**Comment by shamimulalam** [comment]
I'm also waiting for laravel 8 support. Can you please speak out @uxweb . Otherwise, I've to remove this package from my project. Thanks in advance @uxweb :)

**Comment by bumbummen99** [comment]
~~My PR is working in my L8 project. If there are no plans to update i am going to keep it up to date as long as possible as some of my projects depend on it. You can find it here: [skyraptor/sweet-alert](https://github.com/bumbummen99/sweet-alert)~~

It is merged, please do change your temporary versions to uxweb/sweet-alert 2.0.5 👍

**Comment by uxweb** [comment]
@yousefyahya @shamimulalam @bumbummen99 

The PR is now integrated supporting Laravel 8.

Thank you guys.
