### ISSUE TITLE
Facade Alert not found

### ISSUE THREAD

**Issue by NumericFactory** [uxweb/sweet-alert#22]
On Laravel 5.2
First, I installed sweet-alert via composer and add line to providers and aliases in config/app.php
And, I do this in my controller : 
`public function update($id, Request $request) {
    $place = Place::findOrfail($id);
    $place->update($request->all());
    $place->activities()->sync($request->get('activities'));
    // \Session::flash('flash_message', 'success !');
     Alert::message('success !');
    return redirect(route('places.edit', $id));
  }`

And i have this result :
FatalErrorException in PlacesController.php line 61: Class 'App\Http\Controllers\Alert' not found

Can you help me please ?

Thx, Fred

**Comment by djsigfried56** [comment]
Hi NumericFactory,

You need to use Alert
So in your controller specify this:
`use Alert;`

Hope this helps
Greetings

**Comment by uxweb** [comment]
Thanks @djsigfried56 👌
