### ISSUE TITLE
Alert on ajax ?

### ISSUE THREAD

**Issue by ghost** [uxweb/sweet-alert#24]
Hello, Thanks for this awesome package, i have one problem with ajax
how do i display the alert box on ajax request ? it only works when i refresh the browser after ajax request

**Comment by uxweb** [comment]
@DeeJaVu 

Yes, the package is not designed to work with ajax.

You can show the alert after your ajax request is done by using sweet alert javascript api

```
$.post('resource/url', data, function (response) {
    swal("Here's a message!");
});
```
