### ISSUE TITLE
works from routes but not controllers?

### ISSUE THREAD

**Issue by maximusblade** [uxweb/sweet-alert#25]
I cant quite figure out why Alert will only work when I test it in Routes.

but when I implement in my controllers I get no response...no error messages.
Is there something I should be aware of that may "unset" the alert session when it redirects between controllers?
would appreciate some insignt

**Comment by uxweb** [comment]
@maximusblade 

Maybe the way you are importing the Facade within the controller?

```
use Alert;
```
