### ISSUE TITLE
Must always sepecify null in autoclose to have persitnet work?

### ISSUE THREAD

**Issue by gflauder** [uxweb/sweet-alert#28]
Hi,

I seem to require entering a persistent  window like this:
`alert()->warning(trans('surveys.noresponses'), $results['status'])->persistent("OK")->autoclose(null)`

Just entering 

`alert()->warning(trans('surveys.noresponses'),$results['status'])->persistent("OK")`

without a autoclose causes the window to  close as soon as it displays even with Persistent on.

Thanks

Gary

**Comment by uxweb** [comment]
Hi @gflauder 

I just checked `alert()->warning(trans('surveys.noresponses'), $results['status'])->persistent("OK")` and it is working as it should. It never autoclose the alert.

Are you customizing the alert blade view?, maybe you added the autoclose option in the customized view?
