### ISSUE TITLE
not working in alert in redirect()

### ISSUE THREAD

**Issue by mohammad-chavoshipor** [uxweb/sweet-alert#29]
Hi!
not working in alert in redirect()->back();
because working in return view();
why? 
code not working:
`return redirect()->back()`
code working:
`return view('view')`
code alert:
`\Alert::message('Hey!');`
Or:
`alert()->error('Error Message', 'Optional Title');`

**Comment by uxweb** [comment]
Hi @mohamamd-chavoshipor 

I'm doing this test to reproduce your scenario:

```
// This route will show a small form on the root route

Route::get('/', function () {
    return view('welcome');
});

// this route will receive the posted form and redirect back sending an alert
// that will have to show on the / route

Route::post('/redirect-home', function () {

    Alert::message('This will show in home');

    return back();
});
```

This is the small form in my welcome view:

```
    <div class="container">
            <div class="content">
                <div class="title">Laravel 5</div>

                <form method="POST" action="/redirect-home">
                    {{ csrf_field() }}
                    <label for="email">Email</label>
                    <input type="text">
                    <button type="submit">Submit</button>
                </form>
            </div>
        </div>
```

And it is working fine!

Could you give more detail about the issue?, Thanks!

**Comment by wanghanlin** [comment]
It's not working on my side too, and code is same as yours, just some word changes.
my laravel version is v5.2.39

**Comment by dameety** [comment]
Didn't work for me too, any solution?

**Comment by tonywong625** [comment]
Working for me now

need to add to your template

```
    <!-- Include this after the sweet alert js file -->
    @include('sweet::alert')
```
