### ISSUE TITLE
Alerts are not called

### ISSUE THREAD

**Issue by kirykr** [uxweb/sweet-alert#30]
I places "use Alert;" on the top of my UserController.php file
and placed these in the destroy method

```
 public function destroy($id)
    {
        //
        Alert::warning('Warning Message', 'Optional Title');
        alert()->success('You have been logged out.', 'Good bye!');

        User::findOrFail($id)->delete();

        Session::flash('delete_user','The user has been deleted!');

        return redirect('admin/users');
    }
```
# 

They didn't work.. any ideas
Thanks,

**Comment by eullercristian** [comment]
I have a same problem, i am using laravel 5.1

**Comment by eullercristian** [comment]
Its not a problem. I included a css in my template, and its work fine. Thank you.

**Comment by eullercristian** [comment]
@kirykr please close, this issue.

**Comment by uxweb** [comment]
Thanks! @eullercristian
