### ISSUE TITLE
Best Way to get errors Laravel in view partials

### ISSUE THREAD

**Issue by eullercristian** [uxweb/sweet-alert#31]
Hi @uxweb its package is very useful, thank you. Did you try to render error of request in view partial? I tried to use, its works, but the same message is showing two times, the first on a get error, the second,  when i change a page. See my code bellow: 

`@if($errors->any())
    <?php $error=$errors->all()?>
    <?php alert()->error("".$error[0]."", 'Corrija os erros abaixo')->persistent('Fechar') ?>`
    </div>@endif`

Belllow i show how i use in template

`<div class="container">
    <div class="col-md-12">
        @include('admin::partials.message')
    </div>
</div>`

Can you or other member helpe me? :)

**Comment by uxweb** [comment]
@eullercristian 

I see, you are calling the alert twice, once inside your controller and again from your view.

That's why it is displaying another alert after you move from the current page.

What are trying to achieve?
