### ISSUE TITLE
How i pass text html to component

### ISSUE THREAD

**Issue by eullercristian** [uxweb/sweet-alert#32]
Hi @uxweb , how i pass code html to component? 

Example: ` alert()->success('<ul><li>Some Text</li></ul>', 'Errors');`

Its possible?

Thanks one more time. :)

**Comment by uxweb** [comment]
Hi @eullercristian ,

Yes, it is possible:

```
alert()->success('<ul><li>Some Text</li></ul>', 'Errors')->html();
```

**Comment by eullercristian** [comment]
Thanks a lot @uxweb  :)

**Comment by eullercristian** [comment]
Sorry for delay in my response @uxweb , today that i got try this function.

See the print, the component not works using html.

`alert()->success('<ul><li>Some Text</li></ul>', `'Errors')->html();`

returns: https://puu.sh/qqgm9/f1833304f4.png

Can you take a look? Thanks one more time.

**Comment by uxweb** [comment]
@eullercristian Sure, i'm giving it a shot!, thanks!

**Comment by uxweb** [comment]
uhmmm, that's pretty strange, are you using a custom blade template to show the alert? or are you using the included one?

**Comment by eullercristian** [comment]
@uxweb  i am pass the code in my template, see the code bellow: 

`@if (Session::has('sweet_alert.alert'))
    <script>
      swal({
            text: "{!! session('sweet_alert.text') !!}",
            title: "{!! session('sweet_alert.title')  !!}",
            timer: "{!! session('sweet_alert.timer')  !!}",
            type: "{!! session('sweet_alert.type')  !!}",
            showConfirmButton: "{!! session('sweet_alert.showConfirmButton') !!}",
            confirmButtonText: "{!! session('sweet_alert.confirmButtonText') !!}",
            confirmButtonColor: "#AEDEF4"
            // more options
        });
    </script>
@endif`

In method of controller i pass: 

`alert()->success('<ul><li>Some Text</li></ul>','Errors')->html();`

Am I doing something wrong? Thanks a lot

**Comment by uxweb** [comment]
@eullercristian 

You're doing everything ok, but to tell swal to display the text as html, you have to pass it an html property:

```
@if (Session::has('sweet_alert.alert'))
<script>
    swal({
        text: "{!! session('sweet_alert.text') !!}",
        title: "{!! session('sweet_alert.title') !!}",
        timer: "{!! session('sweet_alert.timer') !!}",
        type: "{!! session('sweet_alert.type') !!}",
        showConfirmButton: "{!! session('sweet_alert.showConfirmButton') !!}",
        confirmButtonText: "{!! session('sweet_alert.confirmButtonText') !!}", 
        confirmButtonColor: "#AEDEF4",
        html: "{!! session('sweet_alert.html') !!}"
    });
</script>
@endif
```

That html property is generated by the package when you call the alert()->html() method, you just have to add it to your template.
