### ISSUE TITLE
Unable to use Alert

### ISSUE THREAD

**Issue by warmjaijai** [uxweb/sweet-alert#34]
Dear Developers,

I try to test out the sweetalert however it doesn't work. Some issues popped up as follows:

route.php
`use Alert;

Route::get('test', function(){
    Alert::message('testing');
});`

when I type use Alert like this it pops that 

> ErrorException in routes.php line 3:
> The use statement with non-compound name 'Alert' has no effect

I am not sure if this is a sign where I install it improperly or what. But when I delete `use Alert;` then refresh the localhost:8000/test page, it is just white plain.

I did put 

```
<script src="{{ url('js/sweetalert.min.js') }}"></script>


 <link rel="stylesheet" type="text/css" href="{{ url('css/sweetalert.css') }}">
```

and both are placed in the right files. Please help!

**Comment by uxweb** [comment]
Hi @warmjaijai

Have you added the Alert alias in config/app.php?

**Comment by warmjaijai** [comment]
Yes I have. for both 

```
    UxWeb\SweetAlert\SweetAlertServiceProvider::class,
```

and 

```
    'Alert' => UxWeb\SweetAlert\SweetAlert::class,
```

**Comment by warmjaijai** [comment]
on top of that, does this package support composer installation?

**Comment by jzfan** [comment]
I use laravel 5.2.42, The Alert didn't work!
`public function store(CreateArticle $request)
    {
    	Article::create($request->input());
        Alert::message('Robots are working!');
    	return redirect('/backend/article');
    }`
redirected with no errors, but no alert message.
dont know why.

**Comment by uxweb** [comment]
@warmjaijai yes, this package supports composer installation.

Did you installed it as shown in the docs?
