### ISSUE TITLE
where and how do you set the configuration options?

### ISSUE THREAD

**Issue by illuminate3** [uxweb/sweet-alert#36]
For example:

```
Session::get('sweet_alert.confirmButtonText')
```

Where do I set this?

I have done:

```
Alert::success('Success Message', 'Optional Title')->persistent('Close');
```

Do I just chain?

```
Alert::success('Success Message', 'Optional Title')->confirmButtonText('Close');
```

**Comment by uxweb** [comment]
@illuminate3

Sorry to answer this late,

Actually, not all configuration options from the JavaScript sweet alert are available.

The reason for this is that the package only uses sweet alert to display the simplest of alerts

If you call any of the alert messages like (success|error|warning|info) an alert will be displayed with a message and an optional title and it will be dismissed after a few configurable seconds, and the other type of alert is the one that is persistent it will be shown with a button to let the user dismiss the alert.

As you can see, the package does not mess with alert confirmation or alert callbacks as those features supported by the sweet alert library must be implemented with JavaScript.

Hope this is informative for you.

Thanks for contributing and if you have more questions let me know!.

**Comment by illuminate3** [comment]
thanks
