### ISSUE TITLE
Alerts Appearing again on next page or refresh when using middleware

### ISSUE THREAD

**Issue by valeryan** [uxweb/sweet-alert#38]
I am using the middleware so that standard error messages will come across as a sweet alert. When using middleware I am experience an odd quirk where once the error message is dismissed it is not being cleared from the session. If I brows to another page or refresh the page the same alert will be displayed. It only does this twice. The next page load or refresh will not have an alert. I do not see this behavior when not using the middleware. 

To make sure it was not something in my applications I did a clean install of Laravel 5.3 and setup the sweet alert middleware and I got the same behavior. 

Steps to reproduce. 
1. Install clean instance of Laravel 5.3.
2. Run `php artisan make:auth` to get auth scaffolding.
3. Setup env so that auth can login or present an error message. 
4. Install sweet-alert as described in the readme. (get packages, config, modify view, modify, middleware)
5. Make a failed login attempt to see sweet alert. 
6. browse to forgot password view or refresh to see the second alert. 
7. again refresh or browse to another page to see no third alert is shown.

**Comment by Fershark** [comment]
same issue
