### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by jrean** [uxweb/sweet-alert#4]
Hi,

Do you think you could add a new method `alert()->newMethod('Message', 'title');`?

This method will behave just like other but with NO icon (info ; success ; error). Just a title and a message.

Regards,

**Comment by uxweb** [comment]
Thanks!, i'm working on change the current api for a new one to allow this.

**Comment by uxweb** [comment]
Just released the new version with a change that solves this!.

Hope this will be useful to you

Thanks for contributing!

**Comment by jrean** [comment]
Awesome @uxweb!
:)
