### ISSUE TITLE
Class 'Alert' not found in Laravel 5.3.28

### ISSUE THREAD

**Issue by PsKs** [uxweb/sweet-alert#42]
Hello,
I use Laravel 5.3.28 and I install package form `composer require uxweb/sweet-alert` 
and follow the instruction here. this is my [config/app.php](https://gist.github.com/PsKs/1f756aa8190095ab421b89892d25e9a2) and  my controller [SentinelRegisterController.php](https://gist.github.com/PsKs/9ccd0c2c9ca67342fa2ddd6e193cc80e) 

On browsers I got this error `FatalThrowableError in SentinelRegisterController.php line 17: Class 'Alert' not found` 

And i see in my PhpStorm i see notice 
<img width="213" alt="screen shot 2017-01-03 at 10 54 40 pm" src="https://cloud.githubusercontent.com/assets/7805237/21613802/63ec54ce-d209-11e6-87c0-72f127ef88b4.png">

With helper function `alert()->success('You have been logged out.', 'Good bye!');`
I got `ReflectionException in Container.php line 749: Class uxweb.sweet-alert does not exist`

In view i put `@include('sweet::alert')` after `{!! Html::style('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css') !!} {!! Html::script('assets/global/plugins/bootstrap-sweetalert/sweetalert.min.js') !!}` in `layout.blade.php`

what i mistake? Please help me.
Best Regard.

**Comment by uxweb** [comment]
Hi @PsKs 

It looks as if could not find the package classes. Could you take a look under the `vendor` directory and make sure that the package is there?.

I reviewed your configuration inside app.php and looks ok.

![screen shot 2017-01-04 at 8 32 37 pm](https://cloud.githubusercontent.com/assets/5134732/21667260/f9abfce0-d2bc-11e6-8812-fd377b346ba1.jpg)

**Comment by PsKs** [comment]
@uxweb Thank for your help. 
Yes. Package is here.
But after I try many thing for fix I use `php artisan config:cache` and sleep laptop for rest.
I don't know becuase `php artisan config:cache` or whatever. It work perfectly.

**Comment by uxweb** [comment]
@PsKs 

Glad you could fixed it!

Greetings
