### ISSUE TITLE
Alerts not showing on 5.4.11

### ISSUE THREAD

**Issue by debugdotdog** [uxweb/sweet-alert#46]
So i am trying to at uxweb/sweet-alert to my project that is currently using 5.4.11.
I have used this on many projects before but none since i started using laravel 5.4.11

My Master Layout:
```
<link rel="stylesheet" href="{{url('/css/sweetalert.css')}}">
<link rel="stylesheet" href="{{url('/css/app.css')}}">
<script src="{{url('/js/sweetalert.js')}}"></script>
<script src="{{url('/js/app.js')}}"></script>
@include('sweet::alert')
```

My config/app.php:
`UxWeb\SweetAlert\SweetAlertServiceProvider::class,`

My Controller: 
```
Alert::message('We will get back to you soon!', 'Thank you!');
return redirect()->route('home');
```

I have added `use Auth;` into my controller as well.

**Comment by Nathanw** [comment]
Have you added `'Alert' => UxWeb\SweetAlert\SweetAlert::class,` to your config/app.php? You will also need `use Alert;` at the top of your controller.

**Comment by debugdotdog** [comment]
Yeah I have added both of these.

**Comment by Nathanw** [comment]
Do you receive any error messages? Might be worth trying `composer dump-autoload` or `php artisan config:cache` as mentioned in #42.

**Comment by ramisohail** [comment]
same issue here exactly with 5.3, nothing happening at all

**Comment by debugdotdog** [comment]
Ran both commands, And also tested on a fresh laravel project but still not working. No errors are showing, it just doesn't display the alert.

**Comment by Nathanw** [comment]
I have just created a fresh install of laravel and included this package and everything has worked fine. Are you sure that the following is included on the layout where you want the alert to appear? Also are you sure that these files definitely exist?

```
<link rel="stylesheet" href="{{url('/css/sweetalert.css')}}">
<script src="{{url('/js/sweetalert.js')}}"></script>
@include('sweet::alert')
```

**Comment by ramisohail** [comment]
it worked for me after putting the  @include('sweet::alert') in the Script tag i was just putting it in my view which doesnt work

**Comment by uxweb** [comment]
@doatyjs 

If PHP is not squacking for some errors, maybe this is related to the load of sweetalert assets.

Try figuring out with chrome dev tools if all your assets are being loaded.

I just made a test with a fresh Laravel 5.4.15 installation and it works as expected.

![image](https://cloud.githubusercontent.com/assets/5134732/23584034/dbbeb90c-011a-11e7-89e8-b959ecc26365.png)

If you need more help, please let me know, i'll be happy to help you!

**Comment by uxweb** [comment]
Thank you @Nathanw @ramisohail for helping @doatyjs to try solve this issue 👍
