### ISSUE TITLE
Readme.md - typo's?

### ISSUE THREAD

**Issue by luckyguy73** [uxweb/sweet-alert#47]
on the readme in 3 different places it says sweatalert instead of sweetalert.  i assume this is a typo and probably caused many people's issue when they copy and paste.  do a find on webpage of sweat to see what i mean.  thanks.

<img width="641" alt="screen shot 2017-03-18 at 8 43 45 pm" src="https://cloud.githubusercontent.com/assets/18206189/24077969/cb6d4ee0-0c1b-11e7-9036-cc99469b05cd.png">

**Comment by luckyguy73** [comment]
actually it works when you use SweatAlert, but i think you want it to be Sweet not Sweat, just an fyi if you want to update it

**Comment by uxweb** [comment]
@luckyguy73 Thanks to spot this man! i have fixed those typos 👍
