### ISSUE TITLE
Typos in readme

### ISSUE THREAD

**Issue by randyrankin** [uxweb/sweet-alert#50]
There is a typo in the middleware section ```\UxWeb\SweetAlert\ConvertMessagesIntoSwetAlert::class,```. It should read ```\UxWeb\SweetAlert\ConvertMessagesIntoSweatAlert::class,```

**Comment by randyrankin** [comment]
Also, is there there a typo in the file named uxweb\sweet-alert\src\SweetAlert\ConvertMessagesInto**Sweat**Alert.php? Shouldn't it be \ConvertMessagesInto**Sweet**Alert.php. The same applies to the class name. Is this by design??

**Comment by uxweb** [comment]
@randyrankin 

Those are typos, thanks for finding them!

**Comment by uxweb** [comment]
@randyrankin 

The latest release have all those types fixed

**Comment by randyrankin** [comment]
I guess I could have done a PR but wasn't sure if it was that way for some reason I wasn't seeing. Anyway, thanks for your work on this!
