### ISSUE TITLE
Since Laravel 5.3 we cannot enter Javascript directly in views

### ISSUE THREAD

**Issue by chrisk2204** [uxweb/sweet-alert#56]
What to do now? So I can not configure the sweetAlert messages. But I need a "Do you really want to delete this" dialog with "yes" and "no" option. So I got my controller with a `Session::flash('sweet_alert.alert', $message, null);` line.
In my view I render a partial named '_messages.blade.php where I catch the session messages.
As described in your readme I should enter the javascript here, but since the new Laravel version it will not be rendered. So I did the following:
```
@if(Session::has('sweet_alert.alert'))
	{{ null, alert('<a href="projects.destroy">Delete</a>')->html()->warning('Do you really want to delete this project? This action cannot be undone!', 'Warning')->html()->persistent('No') }}
@endif
``` 

I don't know why the first argument must be a string, so I entered "null". Otherwise it will give me the string as plain text in my view. When I call the html()-function as above, I got the "Delete"-link as huge title in sweetAlert and as message-text "true", followed by the "No"-Button. =( 
Can anyone help me?

**Comment by uxweb** [comment]
Hey @chrisk2204,

The helper alert method is intended to be used from your controllers not in views.

If you want to add extra functionality beyond just "alerting", please check the sweet-alert javascript api https://limonte.github.io/sweetalert2/.

If you need more help, I'll be glad to help!

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io//
