### ISSUE TITLE
type -> icon

### ISSUE THREAD

**Issue by guillenotfound** [uxweb/sweet-alert#59]
According to their documentation seems like that kay might change?

**Comment by zietbukuel** [comment]
@ZiFFeL1992 Are you talking about this?

https://github.com/uxweb/sweet-alert/blob/develop/src/SweetAlert/SweetAlertNotifier.php#L63

If so yeah, I change that line from:

`$this->config['type'] = $type;`

To

`$this->config['icon'] = $type;`

And now it works fine.
