### ISSUE TITLE
SweetAlert2 Compatibility

### ISSUE THREAD

**Issue by joerjoers** [uxweb/sweet-alert#62]
Most of the function are no longer working in SweetAlert2. 
**Example:**
`alert()->success('Message', 'title');` is no longer working as a Success Alert but a normal alert.

**Comment by ashish328** [comment]
the upgraded package of sweetalert1.x to sweetalert2.0 is not working as expected icons are missing while using it.

**Comment by legreco** [comment]
The icons are showing correctly on my side

**Comment by uxweb** [comment]
@joerjoers  

There are some breaking changes in the sweet alert 2 javascript API.

This package is intended to work with v1 of sweet alert javascript.

To Add compatibility with sweet alert 2 I would need to make a new release which will not be backwards compatible.

So the versions will be as:

V1.* => sweet-alert compatible

V2.* => sweet-alert-2 compatible

What do you thing guys? Does this looks good to you?

**Comment by uxweb** [comment]
Ok Guys, I see that the same sweet alert package from npm has upgraded to v2 officially. Then I will upgrade this package to work with the sweet-alert2 javascript library.

I need to review the breaking changes as published here:

https://sweetalert.js.org/guides/#upgrading-from-1x

**Comment by legreco** [comment]
will the upgraded package laravel 5.5 compatible?

**Comment by R00118189** [comment]
@uxweb when can we expect PR merge? and full SweetAlert2 compatibility?

**Comment by uxweb** [comment]
@legreco 
Yes, it is compatible with Laravel 5.*.

@R00118189 
We are working on the new version. It'll be ready for the next week (at the end of October).

Thanks for all your help and support.

**Comment by OGhawsi** [comment]
I am also getting just a normal alert for all types of messages. Can someone help? I am using Laravel 5.5
@uxweb

**Comment by zietbukuel** [comment]
I'm also having this same issue on Laravel 5.5. I'm just getting a normal/regular message popup, changing the type of messages always produces the same result.

**Comment by OGhawsi** [comment]
Does anybody know if the problem is solved because I am running out of time to deploy my app.
Thanks. @uxweb

**Comment by iLongRanger** [comment]
I am also waiting for the update.

**Comment by 23andreas** [comment]
+1

**Comment by OGhawsi** [comment]
I have downloaded both css and js @1.1.3 and worked fine. Here is the link.
https://unpkg.com/sweetalert@1.1.3/dist/

**Comment by magnosis** [comment]
Do you guys have an ETA for v2?

Thank you so much for this package!!
I'm using it with sweetalert 1.1.3 in the meantime, works wonderfully. Great job!!

**Comment by addingama** [comment]
I can make it work with sweetalert 2.

I just need to export the config and view
```
 php artisan vendor:publish --provider "UxWeb\SweetAlert\SweetAlertServiceProvider"
```

 then change the view `resources/view/vendor/sweet/alert.blade.php` to follow sweetalert 2 format

```
@if (Session::has('sweet_alert.alert'))
    <script>
        swal({
            text: "{!! Session::get('sweet_alert.text') !!}",
            title: "{!! Session::get('sweet_alert.title') !!}",
            timer: {!! Session::get('sweet_alert.timer') !!},
            icon: "{!! Session::get('sweet_alert.type') !!}",
            showConfirmButton: "{!! Session::get('sweet_alert.showConfirmButton') !!}",
            confirmButtonText: "{!! Session::get('sweet_alert.confirmButtonText') !!}",
            confirmButtonColor: "#AEDEF4"
        });
    </script>
@endif
```

I hope that can help

**Comment by Wasca** [comment]
@uxweb Just wondering if this is now compatible with SweetAlert2? https://sweetalert2.github.io/

**Comment by uxweb** [comment]
@Wasca @magnosis @iLongRanger @dashracer @OGhawsi 

Guys, I'm very sorry for have making you wait for so long.

v2 is now ready!

I really appreciate all your support.

Best regards

**Comment by doliskani** [comment]
Do not show me the icons too.

**Comment by prafful-panwar-ayur** [comment]
Icon not showing :(

**Comment by chuysbz** [comment]
> I can make it work with sweetalert 2.
> 
> I just need to export the config and view
> 
> ```
>  php artisan vendor:publish --provider "UxWeb\SweetAlert\SweetAlertServiceProvider"
> ```
> 
> then change the view `resources/view/vendor/sweet/alert.blade.php` to follow sweetalert 2 format
> 
> ```
> @if (Session::has('sweet_alert.alert'))
>     <script>
>         swal({
>             text: "{!! Session::get('sweet_alert.text') !!}",
>             title: "{!! Session::get('sweet_alert.title') !!}",
>             timer: {!! Session::get('sweet_alert.timer') !!},
>             icon: "{!! Session::get('sweet_alert.type') !!}",
>             showConfirmButton: "{!! Session::get('sweet_alert.showConfirmButton') !!}",
>             confirmButtonText: "{!! Session::get('sweet_alert.confirmButtonText') !!}",
>             confirmButtonColor: "#AEDEF4"
>         });
>     </script>
> @endif
> ```
> 
> I hope that can help

This is correct. But I had to change swal() function for swal.fire() because sweetalert2 exposes swal() as a class and I kept getting a console error "Cannot call a class as a function".
