### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by iLongRanger** [uxweb/sweet-alert#64]
Hi ,
 Im having some issue when using Alert::success('Success Message', 'Optional Title'); on my controller , its not showing any icons just the text. i do have the css and js file on my directory. how can i fix this ?

**Comment by iLongRanger** [comment]
this is what i get from the chrome's console window, and i dont know how to fix this, 

SweetAlert warning: "showConfirmButton" option has been deprecated. Please use "button" instead. More details: https://sweetalert.js.org/docs/#button

sweetalert.min.js:1 SweetAlert warning: "type" option has been deprecated. Please use "icon" instead. More details: https://sweetalert.js.org/docs/#icon

I already read the documentation and I cant make swal to work on my controller. 
please help. TIA

**Comment by iLongRanger** [comment]
I just gone through the issue about compatibility , I'll just wait for your new release :) thank you !

**Comment by AngusDV** [comment]
on 
\vendor\uxweb\sweet-alert\src\SweetAlert\SweetAlertNotifier.php

change 
 $this->config['type'] = $icon;
to 
 $this->config['icon'] = $icon;
in line 82
