### ISSUE TITLE
Sweet alert doesn't show css image

### ISSUE THREAD

**Issue by stealthAngel** [uxweb/sweet-alert#65]
# edit and solution
Still no css images. This package needs to be updated to sweetalert2. It's better to make an if else session statement and hard code the sweet alert inside it. Alternatively, make a sweetalert.blade page and include it. e.g

```
    @if(session()->has('message'))
        @include('js.sweetAlert', ['message' => session()->get('message'))
    @endif
```
then in blade file js/sweetAlert.blade.php
https://limonte.github.io/sweetalert2/
```
<script>
swal($message)
</script>
```
Until this package gets updated use the above sample. 
# original

The sweet alert doesn't show the image but when I do the javascript it works well.
An image explains everything easier: https://imgur.com/a/E9V5h

code:
```
        use Alert;

        Alert::success('Something went wrong', 'Oops!');
        return view('debug');
```

Javascript code does show the image:

```
<script>
    swal("Good job!", "You clicked the button!", "error");
</script>
```

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/

**Comment by zymawy** [comment]
@limonte How Did You Solve This Issue?

**Comment by stealthAngel** [comment]
I did this by skipping this package and doing it the javascript way.

**Comment by magnosis** [comment]
I had the same issue and everything went back to normal simply by using version 1.1x instead of 2.x of SweetAlert.js
