### ISSUE TITLE
use Alert;

### ISSUE THREAD

**Issue by erenergul** [uxweb/sweet-alert#67]
I put "use Alert;" my controller laravel project 5.5 but It doesn't work ? Do you have any idea why it happened ? I don't understand. I manually add provider and alias by myself still doesn't working at all..

**Comment by iLongRanger** [comment]
I'm having an issue with this as well but I just disregarded it and continue coding. my IDE is highlighting that import and giving me an error message "undefined class". Its still working for me, the alert is still showing its just that alert()->success('Message', 'title'); is no longer working as a Success Alert but a normal alert. same as with issue #62 . still waiting for an update from @uxweb :)

**Comment by mrunalshah** [comment]
I had the same issue and solved it by using the following in the controller:-
`use UxWeb\SweetAlert\SweetAlert as Alert;` 
also don't forget to add following in the blade (parent) file:
`@include('sweet::alert')`

**Comment by nickdavies791** [comment]
You'll need to add the following to your `config/app.php` file underneath 'aliases' to use the alias name rather than the full path.

```php
'aliases' => [

    'Alert' => UxWeb\SweetAlert\SweetAlert::class,

],
```

Then you can `use Alert` in your controller.
