### ISSUE TITLE
Sweet alert window  displaying again when user press back button.How to fix it?

### ISSUE THREAD

**Issue by madaliou** [uxweb/sweet-alert#70]

**Comment by fedeverdi** [comment]
Same Issue here

**Comment by edsonrbispo** [comment]
When the problem is not facing the browser, the alert appears again.

**Comment by uxweb** [comment]
@fedeverdi @edsonrbispo 

This is related on how browsers manage caching, even when messages are taken out from the session, if you go back to a previous page, the bowser will display them.

Any idea on how we can fix this?

**Comment by eng-ahmednasser** [comment]
this will help you 
`<script>
    if (window.performance) {
     var navEntries = window.performance.getEntriesByType('navigation');
     if (navEntries.length > 0 && navEntries[0].type === 'back_forward') {
          console.log('As per API lv2, this page is load from back/forward');
     } else if (window.performance.navigation
          && window.performance.navigation.type == window.performance.navigation.TYPE_BACK_FORWARD) {
          console.log('As per API lv1, this page is load from back/forward');
     } else {
          console.log('This is normal page load');
        @if (Session::has('sweet_alert.alert'))
            swal( {!! Session::get('sweet_alert.alert') !!} );
            {{ Session::forget('sweet_alert.alert') }}    // This will forget the alert data after displaying it :)
        @endif
     }
}
 else {
     console.log("Unfortunately, your browser doesn't support this API");
}
</script>`
