### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by Vladimir86ns** [uxweb/sweet-alert#75]
I just did as it is on documentation:

1)
composer require uxweb/sweet-alert

2)
'providers' => [
    UxWeb\SweetAlert\SweetAlertServiceProvider::class,
 ];

'aliases' => [
    'Alert' => UxWeb\SweetAlert\SweetAlert::class,
];

3)
npm install sweetalert

4)
in controller imported 
use Alert;

in function 
Alert::message('Robots are working!');

5)
in layout included

<link rel="stylesheet" href="css/sweetalert.css">

<script src="js/sweetalert.min.js"></script>
@include('sweet::alert')

After that nothing happened.

Did I miss something?

**Comment by uxweb** [comment]
@Vladimir86ns 

Please, upgrade to v2

**Comment by AngusDV** [comment]
i am have same problem and do instruction of @Vladimir86ns in new version but my problem not solved
