### ISSUE TITLE
Is this updated to v. 2?

### ISSUE THREAD

**Issue by robertotcestari** [uxweb/sweet-alert#76]
Hi, i was using this packaged and decided to upgrade Sweet Alert from v.1 to v.2. 

But the docs for this package still asks for a css file (that is no longer required). I am also getting "deprecated" messages in my console. 

Is this package ready for v. 2 of SweetAlert?

**Comment by RogierWijsman** [comment]
Got it working with

https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js

**Comment by uxweb** [comment]
@robertotcestari 

Now it's ready for v2
