### ISSUE TITLE
[QUESTION] Unknown parameter "buttons" and "icon" on v2.0

### ISSUE THREAD

**Issue by rioaguspermana** [uxweb/sweet-alert#81]
### Versions
* PHP version: 7.2.4 
* Laravel version: 5.6.*
* Uxweb/sweet-alert version: 2.0
* Sweetalert2:  7.26.11

here my composer.json
```
"require": {
        "php": "^7.1.3",
        "consoletvs/charts": "6.*",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "maatwebsite/excel": "^3.0",
        "uxweb/sweet-alert": "^2.0"
},
```
### Configuration
* include .css and .js files from the sweet-alert library.
* include package to service provider and aliases in config/app.php.
* place `@include('sweet::alert')` in blade.
* call sweetalert within controller `Alert::error('Something went wrong', 'Oops!');` 

### The Problem
icon not show up
![2018-08-15 1](https://user-images.githubusercontent.com/22311760/44144192-bb96cd68-a0b0-11e8-8892-90c906198ab8.png)
got this message on console
![2018-08-15 2](https://user-images.githubusercontent.com/22311760/44144212-cb967880-a0b0-11e8-94c2-43993f953101.png)

### Conclusion
for now im using uxweb/sweet-alert v1.4 and sweetalert2 v7.19.2.
somehow i know it was caused by incompatibility from my sweetalert2 lib, if yes can i know which version of sweetalert2 is compatible with v2.0.
if not please tell me out which is causing the problem, or something inccorect in my setup.

**Comment by yoelpc4** [comment]
Try to include .js files from https://unpkg.com/sweetalert@2.1.0/dist/sweetalert.min.js or https://cdn.jsdelivr.net/npm/sweetalert before your `@include('sweet::alert')`

**Comment by rioaguspermana** [comment]
its work thanks and cheers
