### ISSUE TITLE
show alert icon

### ISSUE THREAD

**Issue by azhidhak** [uxweb/sweet-alert#82]
when i use alert ,alert show successful but icon dont display ?

**Comment by AbdullahObaid** [comment]
use this js file https://unpkg.com/sweetalert@2.1.0/dist/sweetalert.min.js instead of the latest sweetalert release

**Comment by azhidhak** [comment]
tnx , solved

**Comment by uxweb** [comment]
@AbdullahObaid @azhidhak 

Thank you. Glad you could solved it!

**Comment by AngusDV** [comment]
go to https://github.com/uxweb/sweet-alert/issues/64
