### ISSUE TITLE
persistent not showing close text

### ISSUE THREAD

**Issue by FMurunga** [uxweb/sweet-alert#83]
`alert()->success('Staff has been deleted successfully', 'Success')->persistent('Close');`
the alert produced by the above code does not have the close button
Edit!!
here is the problem
`sweetalert.min.js:1 SweetAlert warning: "showConfirmButton" option has been deprecated. Please use "button" instead. More details: https://sweetalert.js.org/docs/#button
e.logDeprecation @ sweetalert.min.js:1
sweetalert.min.js:1 SweetAlert warning: "confirmButtonText" option has been deprecated. Please use "button" instead. More details: https://sweetalert.js.org/docs/#button`

you need to update the package to use the latest version of sweetalert

**Comment by schoenico** [comment]
SweetAlert warning: "showConfirmButton" option has been deprecated.

Same problem on my side! Please change, thanks a lot!

**Comment by uxweb** [comment]
@FMurunga @nicobbzsogr 

Please, update to the new version (2.0)

**Comment by behzadcym** [comment]
> @FMurunga @nicobbzsogr
> 
> Please, update to the new version (2.0)

Hi!
I have installed the last version but I still have the same error.

**Comment by behzadcym** [comment]
And another point is that when I use Alert facades it works fine but when I use helper function alert(),nothing shows up!
