### ISSUE TITLE
sweet alert button doesn't appear

### ISSUE THREAD

**Issue by mohamadhs** [uxweb/sweet-alert#84]
Hi
I use sw-2 in my laravel project but persistent button doesn't show

alert()->warning('please wait','my title')->persistent('ok');

Button Ok doesn't show
can anyone help me?

**Comment by uxweb** [comment]
@mohamadhs What version of sweet alert js are you using?

**Comment by mohamadhs** [comment]
> @mohamadhs What version of sweet alert js are you using?

2

**Comment by ootim** [comment]
Hi, I'm experiencing the same issue as well on version 2 and, 
 - Laravel 5.7
 - sweet alert 2.1.2

Any help with this, please?

**Comment by uxweb** [comment]
@mohamadhs @ootim 

Thank you for submitting this issue. I have detected a bug related to persistent behavior. I'm working on fixing it.

Give me some minutes please.

**Comment by uxweb** [comment]
@mohamadhs @ootim

The fix is ready and integrated. Please upgrade to v 2.0.1

**Comment by ootim** [comment]
Hi, thanks!
