### ISSUE TITLE
Missing persistent button when using html in the message (simple fix)

### ISSUE THREAD

**Issue by myurtsev** [uxweb/sweet-alert#85]
If you want to use html in combination with a persistent button, you have to adjust the lines 264 and 265 in SweetAlertNotifier.php. This is because the options 'showConfirmButton' & 'confirmButtonTex' are deprecated.

Example:

`Alert::error('<p>Text</p>', 'Oops!')->html()->persistent('ButtonText');`

Adjust the lines 264 and 265 in SweetAlertNotifier.php;

from

```
$this->config['showConfirmButton'] = true;
$this->config['confirmButtonText'] = $buttonText;
```

to

```
$this->config['buttons'] = true;
$this->config['buttons'] = $buttonText;
```

**Comment by uxweb** [comment]
@myurtsev This is already changed in the new version, please upgrade if you need to use Sweet Alert 2
