### ISSUE TITLE
Not showing messages from Named Error Bags

### ISSUE THREAD

**Issue by eleazarbr** [uxweb/sweet-alert#89]
Hello, for some reason I had problems showing messages from Named Error Bags.

Something like:

```php
return redirect('register')
    ->withErrors($validator, 'login');
```

To access the named ErrorBag it's necessary to do:

```php
{{ $errors->login->first('email') }}
```

so, I had to add the following code to the `ConvertMessagesToSweetAlert.php` middleware:

```php
public function handle($request, Closure $next)
{
     ...

     if ($request->session()->has('errors')) {
            $message = $request->session()->get('errors');
                       
             /* Added new condition */
	     if (!$message->hasBag('default')) {
	       $bagName = array_keys($message->getBags())[0];
	       $message = $message->$bagName;
	      }
	     /* End new condition */

            if (!is_string($message)) {
                $message = $this->prepareErrors($message->getMessages());
            }

            alert()->error($message)->html()->persistent();
        }

        return $next($request);
}
````

It should be improved, but for the moment hope it works for something.
Was there another way to solve it? Thank you.

**Comment by uxweb** [comment]
Thank you @eleazarbr 

Right now this package does not support named error bags. If you know how to implement the feature, please send a PR.

**Comment by eleazarbr** [comment]
Great! Let me see what'd be the best way to do this and make a PR. Regards and nice work.
