### ISSUE TITLE
SHOULD IT WORK ON LARAVEL 5.7 ?

### ISSUE THREAD

**Issue by RajeshwerSoftware** [uxweb/sweet-alert#91]
SWEET ALERT AFTER SUBMIT FORM IN LARAVEL 5.7 NOT WORKING PLEASE HELP ME

**Comment by ackseriam** [comment]
@RajeshwerSoftware  I have not been able to integrate it either. Any solution?

**Comment by ackseriam** [comment]
@uxweb please, help.

**Comment by ludo1960** [comment]
Where to find the JS and CSS files?

**Comment by ludo1960** [comment]
Add at top of blade file
<script src="https://code.jquery.com/jquery-2.2.2.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

then add this to form open method, I'm using laravel collective forms, so adjust to your needs
{!! Form::open([ 'id' => 'my-form', 'method' => 'DELETE', 'route' => ['users.destroy', $user->id], 'onsubmit' => 'validate(event)' ]) !!} 

then add script below form open,

    <script>
    function validate() {
      event.preventDefault(); // prevent form submit
      var form = document.forms["my-form"]; // storing the form
      swal({
             title: "Are you sure?",
             text: "Once deleted, you will not be able to recover this file!",
             icon: "warning",
             buttons: true,
             dangerMode: true,
           })
          .then((willDelete) => {
               if (willDelete) {
                     form.submit();
               } else {
                     return true;
           }
        });
    }
    </script>

**Comment by uxweb** [comment]
> SWEET ALERT AFTER SUBMIT FORM IN LARAVEL 5.7 NOT WORKING PLEASE HELP ME

@RajeshwerSoftware 

Please, can you give more details about your configuration?

**Comment by uxweb** [comment]
@ackseriam 

Sure, could you describe your issue please?

Thanks

**Comment by uxweb** [comment]
@ludo1960 

Javascript and css files can be included within your frontend dependencies:

- Directly in your script tags, just before closing the body tag in your blade layout.
- Installing it with npm/yarn and importing it using the resources/js/bootstrap.js.

If you need more details about it, I am able to guide you on how to do it.

**Comment by uxweb** [comment]
@RajeshwerSoftware @ackseriam @ludo1960 

One thing I need to mention about this package is that it only works as a way of showing alerts using the sweet alert javascript library.

If you need to use it for confirmation dialogs or other features that it has, you need to use the js directly.

**Comment by ludo1960** [comment]
II have it working as my code above, ended up `<script src="{{ asset('js/sweetalert2.min.js') }}"></script>
copying the code from `https://code.jquery.com/jquery-2.2.2.min.js and putting im my public/js folder. Works a treatm Thanks!!

**Comment by sudarakas** [comment]
Same problem, not showing Alert :/
`
 \Mail::to($owner->email)->send(new ContactMail($request));
        
        Alert::success('Success Message', 'Optional Title');
        
        return back();

    }`

**Comment by sudarakas** [comment]
> Same problem, not showing Alert :/
> `
> \Mail::to($owner->email)->send(new ContactMail($request));
> 
> ```
>     Alert::success('Success Message', 'Optional Title');
>     
>     return back();
> 
> }`
> ```

**Working fine, with Laravel 5.7, I fixed my issue**
You should add the following line, to your view file after the jquery file
` <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @include('sweet::alert')`

> 
**{{-- JavaScript Files --}}
    <script src="/js/jquery-3.3.1.min.js"></script>
    <script src="/js/sweetalert.min.js"></script>
    @include('sweet::alert')**
> 

Thanks  👍

**Comment by CreativeKashifQ** [comment]
sweatalert packeage is not working and not displaying any error message i have done everything but result is negative
