### ISSUE TITLE
[POTENTIAL BUG] Sometimes fails to persist session to front-end

### ISSUE THREAD

**Issue by ttomdewit** [uxweb/sweet-alert#95]
Dear maintainer,

First of all thank you for maintaining this package and all the hard work that goes into it.

What I aim to address is the issue that sometimes the SweetAlert modal fails to show. After extensive "research" on my end, I hope to create an informative issue that is descriptive enough for us to work on, given you have the time.

**Step by step scenario**:

1. I have a simple form with a single text input
1. I press the "Submit" button programatically (_when the simple text input reaches 36 characters, the form is submitted via jQuery_)
1. When the form is submitted, it reaches my `store` method on my Controller
1. When the form is done processing, we _redirect_ back to the original form

Between step 3 and 4 are some complications. The form will be handled within the Controller, but the outcome varies on the given request data (the 36 characters).

If, for example, the 36 characters do not exist in the database, a "positive" flow should be handled. If, for example, the 36 characters already exist, the negative flow is to be triggered.

In theory, both flows work flawlessly, as my log files show.

**How did I log the information I needed?**

I added a use-case specific Log channel in Laravel 5.8 (https://laravel.com/docs/5.8/logging).

```php
Log::channel('use-case-keyword')->info(__FILE__ . ':' . __LINE__);
```

Via the above code I was able to trace where the flow would take me and from this information (I have 17 lines of code like this in the entire `store` method) it came to my attention that, as previously mentioned, the flow works as it is supposed to.

Next, I added the following code to the Blade-file which holds the form:

```php
@if(Session::has('sweetalert.json'))
    {{ \Illuminate\Support\Facades\Log::channel('use-case-keyword')->info(str_repeat('>', 50)) }}
    {{ \Illuminate\Support\Facades\Log::channel('use-case-keyword')->info(__FILE__ . ':' . __LINE__) }}
    {{ \Illuminate\Support\Facades\Log::channel('use-case-keyword')->info('app.blade.php:47') }}
    {{ \Illuminate\Support\Facades\Log::channel('use-case-keyword')->info(json_encode(Session::get('sweetalert.json'), JSON_PRETTY_PRINT)) }}
    {{ \Illuminate\Support\Facades\Log::channel('use-case-keyword')->info(str_repeat('<', 50)) }}
@endif
@include('sweetalert::view')
```

I appreciate this is extensive and possibly overkill, but I wanted to be sure I was logging every single possible line of information prior to submitting this issue/support request.

What you'll notice is the following lines of code:

```php
Log::channel('use-case-keyword')->info(str_repeat('>', 50))
Log::channel('use-case-keyword')->info(str_repeat('<', 50))
```

The previous lines will simply store a bunch of `>` and `<` in my Log-file, allowing me to narrow down on different requests to the form.

This allowed me to more easily search between the Log entries and, unfortunately, showed me entries that started with `<` and ended with `>` the line after, whereas, as you can see, I was expecting some SweetAlert-specific information.

**When does this happen?**

As I can tell very randomly. As my Log entries show, on July 6th of this year, I had ±100 errors (no notification) and ±400 notifications (be it both error notifications or positive notifications, depending on the flow).

Thank you for taking the time to read into this issue and hopefully we can find a solution to the problem(s) described.

Tom de Wit

**Comment by uxweb** [comment]
@ttomdewit 

Hello Tom,

Sorry for my late answer to this issue. I am working on improving the code that flashes the configuration to the Laravel session. Maybe this can solve this and other issues related to session data.

I'll let you know in this issue when the new release is out!

Please stay tuned!

**Comment by uxweb** [comment]
@ttomdewit 

Hello Tom,

The new release is out!

Thank you!
